version: 0.2 
os: linux
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  build:
    commands:
       - aws s3 sync s3://codepipeline-us-east-1-88321018183 s3://newbucket45151 --source-region us-east-1 --region us-east-1
